name: ${dxve.name}
version: ${dxve.version}
main: de.dxve.dTeamChat.DTeamChat
api-version: '1.21'
authors: [ Dxve ]
website: https://dxve.de

commands:
    dteamchat:
        description: 'TeamChat command'
        aliases:
            - teamchat
            - tc